### PR TITLE
Enable traffic quality feature flag

### PR DESCRIPTION
**Pull request by malmstein**
**Asana Task/Github Issue:** https://app.asana.com/0/1174433894299346/1208888211876104/f

## Description
Enable Traffic Quality Feature Flag

### Feature change process:

- [ ] I have added a [schema](https://github.com/duckduckgo/privacy-configuration/tree/main/schema) to validate this feature change
- [ ] I have tested this change locally
- [ ] This code for the config change is ready to merge
- [ ] This feature was covered by a tech design

#### Additional info:

- [x] I have tested this change locally in all supported browsers
- [x] This change will be visible to users
- [x] This code for the config change is ready
- [ ] This change was covered by a ship review

#### Brief explanation
- Reported URL:
- Problems experienced:
- Platforms affected:
  - [ ] iOS
  - [x] Android
  - [ ] Windows
  - [ ] MacOS
  - [ ] Extensions
- Tracker(s) being unblocked:
- Feature being disabled:

- [x] I have referenced the URL of this PR as the "reason" value for the exception (where applicable).
- [x] This change is a speculative mitigation to fix reported breakage.

#### Reference

-   [Config Reviewer Documentation](https://app.asana.com/0/1200890834746050/1204443212791216/f)
-   [Config Maintainer Documentation](https://app.asana.com/0/1200890834746050/1200573250322769/f)
-   [Feature Implementer Documentation](https://app.asana.com/0/1200890834746050/1201498956177210/f)

### CODE REVIEW

**Comment by malmstein** [comment]
@jonathanKingston there seems to be some issues with the Test workflow, TDS.

**Comment by jonathanKingston** [comment]
> there seems to be some issues with the Test workflow, TDS.

I don't see any changes in the 'files changed'. What's up?

Can you mark me as a reviewer as my github notifications are a dumpster fire (or ping on MM) 😆

**Review by jonathanKingston — APPROVED** [review]

**Comment by malmstein** [comment]
thanks @jonathanKingston !

**Review by nalcalag — APPROVED** [review]
LGTM! Maybe 'targetVersions' would be a clearer name as @jonathanKingston mentioned, but since it was already agreed upon in Asana, I'll leave it up to you.

**Pull request merged**
