### PR TITLE
Enable phishing protection for internal users

### PR DESCRIPTION
**Pull request by alessandroboron**
**Asana Task/Github Issue:**

## Description

Enable Phishing Detection feature flag for internal users [iOS]

#### Reference

-   [Config Reviewer Documentation](https://app.asana.com/0/1200890834746050/1204443212791216/f)
-   [Config Maintainer Documentation](https://app.asana.com/0/1200890834746050/1200573250322769/f)
-   [Feature Implementer Documentation](https://app.asana.com/0/1200890834746050/1201498956177210/f)

### CODE REVIEW

**Review by quanganhdo — APPROVED** [review]
Changes LGTM

**Comment by alessandroboron** [comment]
> Changes LGTM

Thanks for the speedy review @quanganhdo !

**Comment by jonathanKingston** [comment]
This should have a features/ file describing the feature. (I'll add linting to prevent this happening in future)

**Review by jonathanKingston — CHANGES_REQUESTED** [review]
Can you create a features/ file for this change please

**Comment by jonathanKingston** [comment]
I created: https://github.com/duckduckgo/privacy-configuration/pull/2484 to ensure this doesn't happen in future :)

**Review by jonathanKingston — APPROVED** [review]
Sorry, I'm not sure why I missed the other file!

**Pull request merged**
