### PR TITLE
Brad/config pixel test

### PR DESCRIPTION
**Pull request by SlayterDev**
**Asana Task/Github Issue:** https://app.asana.com/0/72649045549333/1207165680693234/f

## Description

This PR enables the background config pixel test for iOS and macOS

#### Reference
- [Config Reviewer Documentation](https://app.asana.com/0/1200890834746050/1204443212791216/f)
- [Config Maintainer Documentation](https://app.asana.com/0/1200890834746050/1200573250322769/f)
- [Feature Implementer Documentation](https://app.asana.com/0/1200890834746050/1201498956177210/f)

### CODE REVIEW

**Comment by samsymons** [comment]
Looks like the diff action is failing due to a conflict, not sure what's up there.

**Comment by SlayterDev** [comment]
> Looks like the diff action is failing due to a conflict, not sure what's up there.

Yes. There was a conflict I resolved last week but the CI is stuck.

**Review by dharb — DISMISSED** [review]
👍

**Review by dharb — APPROVED** [review]
👍

**Pull request merged**
