### PR TITLE
Enable ctl mac

### PR DESCRIPTION
**Pull request by SlayterDev**
https://app.asana.com/0/0/1201694797383792/f

Enables Click to Load on mac.

Corresponding PR: https://github.com/more-duckduckgo-org/macos-browser/pull/329

### CODE REVIEW

**Comment by jonathanKingston** [comment]
How is the commit log so convoluted? Is your local main history broken?

**Comment by ladamski** [comment]
@jonathanKingston @SlayterDev would it be easier to merge https://github.com/duckduckgo/privacy-configuration/pull/119 instead?  Same thing just that Brad had his ready first :)

**Comment by SlayterDev** [comment]
@ladamski just going to give the mac code a quick check to ensure the config checks are properly implemented before merging. Should be done by EoD.

**Comment by ladamski** [comment]
@SlayterDev I'm not currently checking for the enable flag yet because this config is disabled, so if I checked for it nobody could test the feature :)

**Pull request closed without merging**
