### PR TITLE
Revert "Fixing banks with reported broken logins (#1290)"

### PR DESCRIPTION
**Pull request by kzar**
This reverts commit 0d2d1e4c395419c015c4f0dfb6b390e3bed1f159. The
change led to a rise in breakage reports, so we will revert for now.

**Asana Task/Github Issue:** https://app.asana.com/0/inbox/1200776578788342/1205444681224576/1205452538213955/f

#### Reference
- [Config Reviewer Documentation](https://app.asana.com/0/1200890834746050/1204443212791216/f)
- [Config Maintainer Documentation](https://app.asana.com/0/1200890834746050/1200573250322769/f)
- [Feature Implementer Documentation](https://app.asana.com/0/1200890834746050/1201498956177210/f)

### CODE REVIEW

**Comment by ladamski** [comment]
@kzar do you think this issue is due to moving that handful of entries from the temporary allowlist to the feature-specific allowlists?  Or that people complained about trackers not being blocked on those sites?

**Comment by kzar** [comment]
> @kzar do you think this issue is due to moving that handful of entries from the temporary allowlist to the feature-specific allowlists? Or that people complained about trackers not being blocked on those sites?

I'm not sure, I thought it was safest to revert the change entirely as I'm not too familiar with it. (Rather than trying to tweak it, or partially revert.)

**Comment by laghee** [comment]
> If that follows the instructions that Jason provided I think we should be good with the revert 👍

There were 2 different cases -- this was the nuclear option. There's another option that should fix for android/extension where the complaints are. If that's what we want, I can push a commit here.

**Comment by kzar** [comment]
We've decided to take a less drastic approach, closing this out for now.

**Pull request closed without merging**
