### PR TITLE
Disable Android NTP Experiment

### PR DESCRIPTION
**Pull request by malmstein**
**Asana Task/Github Issue:** https://app.asana.com/0/1174433894299346/1208246088003096/f

## Description
Remove NTP experiment

#### Reference
- [Config Reviewer Documentation](https://app.asana.com/0/1200890834746050/1204443212791216/f)
- [Config Maintainer Documentation](https://app.asana.com/0/1200890834746050/1200573250322769/f)
- [Feature Implementer Documentation](https://app.asana.com/0/1200890834746050/1201498956177210/f)

### CODE REVIEW

**Review by joshliebe — APPROVED** [review]
LGTM!

**Review by nalcalag — APPROVED** [review]
LGTM but I'll leave some feedback:

1. It is recommended to disable the feature before remove it forever because there will be kept cached as true for users who have it. More info in [Documentation](https://app.asana.com/0/1202561462274611/1203928902316231/f)
2. You can leave variants with weight 0 so you can still measure existing users assigned to experiment without allocating variants to new users. So feel free to leave it if this is something you are interesting in.

**Comment by malmstein** [comment]
Thanks @joshliebe @nalcalag !

**Review by marcosholgado — APPROVED** [review]
LGTM

**Pull request merged**
